//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Packages.Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Packages.Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 行政区划,行政区划代码
        ///北京市,110000
        ///东城区,110101
        ///西城区,110102
        ///朝阳区,110105
        ///丰台区,110106
        ///石景山区,110107
        ///海淀区,110108
        ///门头沟区,110109
        ///房山区,110111
        ///通州区,110112
        ///顺义区,110113
        ///昌平区,110114
        ///大兴区,110115
        ///怀柔区,110116
        ///平谷区,110117
        ///密云区,110228
        ///延庆区,110229
        ///天津市,120000
        ///和平区,120101
        ///河东区,120102
        ///河西区,120103
        ///南开区,120104
        ///河北区,120105
        ///红桥区,120106
        ///东丽区,120110
        ///西青区,120111
        ///津南区,120112
        ///北辰区,120113
        ///武清区,120114
        ///宝坻区,120115
        ///滨海新区,120116
        ///宁河区,120117
        ///静海区,120118
        ///蓟州区,120119
        ///河北省,130000
        ///石家庄市,130100
        ///长安区,130102
        ///桥东区,130103
        ///桥西区,130104
        ///新华区,130105
        ///井陉矿区,130107
        ///裕华 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 行政区划代码 {
            get {
                return ResourceManager.GetString("行政区划代码", resourceCulture);
            }
        }
    }
}
